### ISSUE TITLE
2 laba

### ISSUE THREAD

**Issue by jovfer** [Andrey-Boldyrev/Labs_cpp#1]
1) Неправильная структура по файлам:
* в заголовочном файле должно лежать только описание класса и функций (account.h)
* реализация методов класса account.cpp
* laba2.cpp или как угодно его называйте (часто называют main.cpp, чтобы было сразу видно где точка входа в приложение) - остальные функции, не имеющие прямого отношения к классу. мейн, хэлперы, общая проверка пользовательского ввода, итд

2) перевод в валюту не должен менять состояние экземпляра класса, только возвращать число, получившееся после перевода

Это после беглого просмотра, возможно на паре замечу еще мелочи, но не существенно скорее всего

**Comment by Andrey-Boldyrev** [comment]
Все исправил, залил исправленную.

**Comment by jovfer** [comment]
@Andrey-Boldyrev прошу прощения что не заметил сразу, но 
3. перегрузка операторов  `+` и `-` выглядит не очень логичной. Предлагаю их логику применить для операторов `+=` и `-=`
