### ISSUE TITLE
Остатки старого кода в 3 лабе

### ISSUE THREAD

**Issue by jovfer** [Andrey-Boldyrev/Labs_cpp#2]
После правок остались лишние закомментированные строчки, надо их удалить. А так похоже на правду.
https://github.com/Andrey-Boldyrev/Labs_cpp/blob/6f4afd4b196fe821e2adcbbc7accc1683fc02edc/Laba_3/Laba_3/List.cpp#L26
https://github.com/Andrey-Boldyrev/Labs_cpp/blob/6f4afd4b196fe821e2adcbbc7accc1683fc02edc/Laba_3/Laba_3/List.cpp#L44

**Comment by Andrey-Boldyrev** [comment]
Удалил
